### PR TITLE
Restaurant page built with JS

### PR DESCRIPTION
**Pull request by m15e**
- [ ] dynamically rendered restaurant website 

- [ ] tab links trigger JS function to change site content

### CODE REVIEW

**Comment by m15e** [comment]
Dear TSE, I am aware that the ESlint checks are not passing, it is recommending to use "export default" to export my modules however adding "default" breaks the code, which is why I am submitting now in hope that you would be able to provide guidance on how to remedy this issue. Any further advise on improving the project would also be appreciated. Thank you in advance.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @m15e 
### You have done well so far :clap: However, you have a few issues to fix:-
- [ ] Add .vscode directory to .gitignore file as it is no longer required as part of the application files
- [ ] Install all the required dependencies, configure and run their commands `npx eslint .` and `npx stylelint "**/*.{css,scss}"` Use this to solve the errors in the pull request branch - html-in-js-feature [Follow this guide](https://github.com/microverseinc/linters-config/tree/master/javascript)
- [ ] Add more scripts in the package.json file by installing all the required dependencies for the scripts to work. See below
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" 
  },
```
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Comment by m15e** [comment]
Dear Second Reviewer, please take a look at my initial comment regarding the ESLint errors, as they we're ignored by @rOluochKe , also his request to add webpack-dev-server and build script are not part of the project specification (watch is used in builds place). If I am mistaken by this please let me know and I'll be happy to correct the error.

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi @m15e! Well done working on the suggested changes from the last review. You linter errors, try this:
- [x] change your import statements e.g. `import { loadAbout } from './modules/about';` to `import loadAbout from './modules/about';`
- [x] add the `default` export statement like before.
Adding the above changes to your project locally resolved the errors on my end.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Review by trekab — APPROVED** [review]
### Approved! :tada: 
Well done @m15e! You may merge the PR and proceed to the next project!

__[Note]__ Please update your README to reflect that this is the `Restaurant Page` project, not `JS Book Library`.

_Happy coding!_ :wave:

**Pull request merged**
